### ISSUE TITLE
Video Calling

### ISSUE THREAD

**Issue by Raghu1124** [Raghu1124/Chatzen#1]
Add video calling feature to the app which allow to video call between two users

**Comment by spyderrr007** [comment]
Hey @Raghu1124,
I wish to express my interest in addressing this particular issue. Would you kindly consider assigning it to me? Your assistance in this matter is greatly appreciated. Thank you.

**Comment by Raghu1124** [comment]
hello @rishirajm007 , good to see that you are have interest in the issue, move on and contribute for the issue.
