### ISSUE TITLE
Logo for the app

### ISSUE THREAD

**Issue by Raghu1124** [Raghu1124/Chatzen#5]
Suggest some logo for the app as the name is Chatzen (a chatting app with privacy features and video calling)

**Comment by OsauravO** [comment]
![logo](https://github.com/Raghu1124/Chatzen/assets/123803605/6da2bae9-a3b5-4d4d-8f23-61ce49a565a7)

**Comment by Raghu1124** [comment]
Hello @OsauravO , good to see that you are interested in the issue, so I had assigned you the issue and this logo looks good but I suggest you to make some changes, if you think can make it more better like any color change or to change element of logo, and update it here, and if you think no changes were required, update me i will merge this one, just send the PR

**Comment by Raghu1124** [comment]
> Suggest some logo for the app as the name is Chatzen (a chatting app with privacy features and video calling)

For the people working on this repo, just add .png or .jpg or whatever your logo type is, add it as a file or a folder in the cloned repository, and create the PR

**Comment by Raghu1124** [comment]
@OsauravO , there was a bug from my side in the hacktoberfest topic label and i think your PR was not contributing in hacktoberfest till now, but now I corrected the bug and if the PR was not contributing, write it to me, i will assign it to you again and make a new PR, i will merge it again and this time it will work.
Sorry for the inconvenience.

**Comment by OsauravO** [comment]
Thanks @Raghu1124 , but i think it worked as it is showing it is under seven-day review period.
![image](https://github.com/Raghu1124/Chatzen/assets/123803605/f04cfae9-70ef-4e1b-bedd-50c7ce23d132)
